### ISSUE TITLE
Timezone lost in method 'add_one_point'

### ISSUE THREAD

**Issue by sinaptik** [AlbinLind/dawarich-api#1]
Firstly, thank you for this and the dawarich homeassistant integration. I think I have found a small bug with timezones.

When using the dawarich homeassistant integration, the time displayed on dawarich is incorrect:

Expected: `2024-12-14 16:06:42 -0800`
Actual: `2024-12-14 08:06:42 -0800`

I think this line: https://github.com/AlbinLind/dawarich-api/blob/main/dawarich_api/api_calls.py#L101

Should be `time_stamp = datetime.datetime.now().astimezone()` to keep timezone information:

Without `.astimezone()`: `2024-12-14T17:20:07.429599`
With `.astimezone()`: `2024-12-14T17:20:07.429599-08:00`

**Comment by sinaptik** [comment]
I've tested this successfully by adding a new line here: https://github.com/AlbinLind/dawarich-home-assistant/blob/e1b81a153129a9509308ca28d06cb531ffea1c57/custom_components/dawarich/device_tracker.py#L109

`time_stamp=datetime.datetime.now().astimezone(),`

**Comment by AlbinLind** [comment]
Thanks a lot for this note, and I am happy you enjoy it. It is indeed true that this is the case, and how it should work, I'll merge your pull request and bump the versions, so keep an eye out for the update!
